[package]
name = "verikron"
version = "0.1.0"
edition = "2024"

[dependencies]
bit-vec = "0.8.0"
rayon = "1.11.0"
rustc-hash = "2.1.1"
smallvec = "1.15.1"

[dev-dependencies]
proptest = "1.9.0"
rand = "0.9.2"
rand_chacha = "0.9.0"
